<?php $billingAddress = $this->getOrder()->getBillingAddress(); 
/*echo '<pre>';
print_r($billingAddress);
die;*/
?>
<div id="order-addresses">
        <div id="order-billing_address" class="box-left">
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head fieldset-legend head-billing-address">Billing Address</h4>    
                </div>

                <fieldset class="np">
                    <div class="order-address" id="order-billing_address_fields">
                        <div class="content">
                            <div class="hor-scroll">
                                <table cellspacing="0" class="form-list">
                                    <tbody>
                                        <tr>
                                            <td class="label"><label>Street</label></td>
                                            <td class="value">
                                                <div><input name="billing[street]"
                                                    value="<?php echo $billingAddress['street']; ?>" type="text" readonly >
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="label"><label>Zip Code</label></td>
                                            <td class="value">
                                                <input name="billing[postcode]"
                                                    value="<?php echo $billingAddress['postcode']; ?>" type="number" readonly>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="label"><label>State</label></td>
                                            <td class="value">
                                                <input name="billing[region]"
                                                    value="<?php echo $billingAddress['region']; ?>" type="text" readonly >
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="label"><label>City </label></td>
                                            <td class="value">
                                                <input name="billing[city]" value="<?php echo $billingAddress['city']; ?>" type="text"  readonly>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="label"><label>Country</label>
                                            </td>
                                            <td class="value">
                                                <input name="billing[country_id]"
                                                    value="<?php echo $billingAddress['country_id']; ?>" type="text" readonly >
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
    </form>