<?php $items = $this->getOrder()->getOrderItems();
/*echo '<pre>';
print_r($items->getData());
die;*/ ?>
    <div id="order-items">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-cart">Ordered Item List</h4>
            </div>

            <div class="grid" id="itemGrid">
                <table cellspacing="0" class="data order-tables">
                    <thead>
                        <tr class="headings">
                            <th class="no-link">Id</th>
                            <th class="no-link">Product Name</th>
                            <th class="no-link">Price</th>
                            <th class="no-link">Quantity</th>
                            <th class="no-link">Discount</th>
                        </tr>
                    </thead>

                    <tbody>
                        <?php if($items->getData()): ?>
                        <?php foreach ($items->getData() as $item): ?>
                        <tr>
                            <td ><?php echo $item['order_item_id']; ?></td>
                            <td ><?php echo $item['name']; ?></td>
                            <td ><?php echo $item['price']; ?></td>
                            <td ><?php echo $item['quantity']; ?></td>
                            <td ><?php echo $item['discount']; ?></td>

                        </tr>
                        <?php endforeach; ?>
                        <?php else: ?>
                        <td class="empty-text a-center" colspan="100">No Items</td>
                        <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>