<?php 
$shippingMethods = $this->getShippingMethods();
$cart = $this->getCart();
/*echo '<pre>';
print_r($cart->shipping_method);
die;*/ ?>
<form id="shippingForm" method="post"
    action="<?php echo $this->getUrl('*/*/saveShippingMethod'); ?>">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <div id="order-shipping_method" class="box-right">
        <div>
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="fieldset-legend head-shipping-method icon-head" >Shipping Method</h4>
                    <div class="form-buttons"><input type="submit" class="scalable add" value="Save"></div>
                </div>
                <div class="fieldset">
                    <div id="order-shipping-method-choose" style="height:98px">
                        <?php foreach ($shippingMethods as $shippingMethod => $value): ?>
                        <dl class="shipping-methods">
                            <dd>
                                <ul>
                                    <li>
                                        <input  type="radio" name="shippingmethod"
                                            value="<?php echo $shippingMethod.' '.$value->getConfigData('price'); ?>"  <?php if($shippingMethod == $cart->shipping_method): ?> checked <?php endif; ?>>
                                        <label class="normal">
                                            <?php echo $value->getConfigData('name').'    '.$value->getConfigData('price'); ?>
                                        </label>

                                    </li>
                                </ul>
                            </dd>
                        </dl>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>