<?php $billingAddress = $this->getBillingAddress(); 
/*echo '<pre>';
print_r($billingAddress);
die;*/
?>
<br>
<div id="order-addresses">
    <form id="billingAddressForm" method="post"
        action="<?php echo $this->getUrl('*/*/saveBillingAddress'); ?>">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div id="order-billing_address" class="box-left">
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head fieldset-legend head-billing-address">Billing Address</h4>
                    <button type="submit" name="button" style="float: right;">Save</button>    
                </div>

                <fieldset class="np">
                    <div class="order-address" id="order-billing_address_fields">
                        <div class="content">
                            <div class="hor-scroll">
                                <table cellspacing="0" class="form-list">
                                    <tbody>
                                        <tr>
                                            <td class="label"><label>Street<span class="required">*</span></label></td>
                                            <td class="value">
                                                <div><input name="billing[street]"
                                                    value="<?php echo $billingAddress['street']; ?>" type="text" class=" input-text required-entry" required>
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="label"><label>Zip Code<span class="required">*</span></label></td>
                                            <td class="value">
                                                <input name="billing[postcode]"
                                                    value="<?php echo $billingAddress['postcode']; ?>" type="number" class=" input-text required-entry" required>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="label"><label>State<span class="required">*</span></label></td>
                                            <td class="value">
                                                <input name="billing[region]"
                                                    value="<?php echo $billingAddress['region']; ?>" type="text" class=" input-text required-entry" required>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="label"><label>City <span class="required">*</span></label></td>
                                            <td class="value">
                                                <input name="billing[city]" value="<?php echo $billingAddress['city']; ?>" type="text" class=" input-text required-entry" required>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="label"><label>Country<span class="required">*</span></label>
                                            </td>
                                            <td class="value">
                                                <input name="billing[country_id]"
                                                    value="<?php echo $billingAddress['country_id']; ?>" type="text" class=" input-text required-entry" required>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="order-save-in-address-book">
                            <input type="checkbox" name="saveInAddressBook" >
                            <label>Save in address book</label>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
    </form>